<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-14T12:59:36 IST" name="Login" finished-at="2024-05-14T13:00:12 IST" duration-ms="36653">
    <groups>
    </groups>
    <test started-at="2024-05-14T12:59:36 IST" name="Add_Buyer_Testcase" finished-at="2024-05-14T13:00:12 IST" duration-ms="36653">
      <class name="Testcases.Add_Buyer_Testcase">
        <test-method is-config="true" signature="beforeclass()[pri:0, instance:Testcases.Add_Buyer_Testcase@c430e6c]" started-at="2024-05-14T12:59:36 IST" name="beforeclass" finished-at="2024-05-14T12:59:36 IST" duration-ms="331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeclass -->
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.String)[pri:0, instance:Testcases.Add_Buyer_Testcase@c430e6c]" started-at="2024-05-14T12:59:36 IST" name="setup" finished-at="2024-05-14T12:59:44 IST" duration-ms="8517" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://192.168.1.9/contract_farming/admin/login]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Add_Buyer_With_all_Valid_Data()[pri:0, instance:Testcases.Add_Buyer_Testcase@c430e6c]" started-at="2024-05-14T12:59:44 IST" name="Add_Buyer_With_all_Valid_Data" finished-at="2024-05-14T13:00:11 IST" duration-ms="26643" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Data was not added successfully expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Data was not added successfully expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at Testcases.Add_Buyer_Testcase.Add_Buyer_With_all_Valid_Data(Add_Buyer_Testcase.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Add_Buyer_With_all_Valid_Data -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Testcases.Add_Buyer_Testcase@c430e6c]" started-at="2024-05-14T13:00:11 IST" name="teardown" finished-at="2024-05-14T13:00:12 IST" duration-ms="734" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:Testcases.Add_Buyer_Testcase@c430e6c]" started-at="2024-05-14T13:00:12 IST" name="endReport" finished-at="2024-05-14T13:00:12 IST" duration-ms="336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- Testcases.Add_Buyer_Testcase -->
    </test> <!-- Add_Buyer_Testcase -->
  </suite> <!-- Login -->
</testng-results>
